<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[bMethods is started]]>
    </line>
    <line>
      <![CDATA[bmethods is failed]]>
    </line>
    <line>
      <![CDATA[cMethods is started]]>
    </line>
    <line>
      <![CDATA[c is running ]]>
    </line>
    <line>
      <![CDATA[cmethods is successfull executed]]>
    </line>
    <line>
      <![CDATA[dMethods is started]]>
    </line>
    <line>
      <![CDATA[d is running ]]>
    </line>
    <line>
      <![CDATA[dmethods is successfull executed]]>
    </line>
    <line>
      <![CDATA[aMethods is started]]>
    </line>
    <line>
      <![CDATA[amethods is skipped]]>
    </line>
  </reporter-output>
  <suite started-at="2024-08-08T13:35:49 IST" name="Default suite" finished-at="2024-08-08T13:35:49 IST" duration-ms="123">
    <groups>
    </groups>
    <test started-at="2024-08-08T13:35:49 IST" name="Default test" finished-at="2024-08-08T13:35:49 IST" duration-ms="123">
      <class name="testNgListenerStudy.MyClass">
        <test-method signature="b()[pri:0, instance:testNgListenerStudy.MyClass@2a5c8d3f]" started-at="2024-08-08T13:35:49 IST" name="b" finished-at="2024-08-08T13:35:49 IST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed methods
at org.testng.Assert.fail(Assert.java:111)
at testNgListenerStudy.MyClass.b(MyClass.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[bMethods is started]]>
            </line>
            <line>
              <![CDATA[bmethods is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method signature="c()[pri:0, instance:testNgListenerStudy.MyClass@2a5c8d3f]" started-at="2024-08-08T13:35:49 IST" name="c" finished-at="2024-08-08T13:35:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[cMethods is started]]>
            </line>
            <line>
              <![CDATA[c is running ]]>
            </line>
            <line>
              <![CDATA[cmethods is successfull executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
        <test-method signature="d()[pri:0, instance:testNgListenerStudy.MyClass@2a5c8d3f]" started-at="2024-08-08T13:35:49 IST" name="d" finished-at="2024-08-08T13:35:49 IST" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[dMethods is started]]>
            </line>
            <line>
              <![CDATA[d is running ]]>
            </line>
            <line>
              <![CDATA[dmethods is successfull executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- d -->
        <test-method signature="a()[pri:0, instance:testNgListenerStudy.MyClass@2a5c8d3f]" started-at="2024-08-08T13:35:49 IST" name="a" finished-at="2024-08-08T13:35:49 IST" depends-on-methods="testNgListenerStudy.MyClass.b" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testNgListenerStudy.MyClass.a() on instance testNgListenerStudy.MyClass@2a5c8d3f depends on not successfully finished methods 
[testNgListenerStudy.MyClass.b() on instance testNgListenerStudy.MyClass@2a5c8d3f]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testNgListenerStudy.MyClass.a() on instance testNgListenerStudy.MyClass@2a5c8d3f depends on not successfully finished methods 
[testNgListenerStudy.MyClass.b() on instance testNgListenerStudy.MyClass@2a5c8d3f]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[amethods is skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- a -->
      </class> <!-- testNgListenerStudy.MyClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
